---
- name: Setting facts so that they will be persisted in the fact cache
  ansible.builtin.set_fact:
    pg_version_to_install: "{{ lookup('env', 'VERSION') | replace('ppg-','') }}"

- name: End play on Ubuntu 26 and versions older than 17.10
  meta: end_host
  when: ansible_distribution == "Ubuntu" and
    ansible_distribution_major_version == "26" and
    pg_version_to_install | string is version('17.10', '<', strict=True)

- name: End play on RedHat 10 and 17.5 and older versions
  fail:
    msg: "Stopping execution on rhel 10 because 17.5 and below are not supported."
  when: ansible_os_family == "RedHat" and
    ansible_distribution_major_version == "10" and
    pg_version_to_install | string is version('17.5', '<=', strict=True)

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: install Percona Platform for PostgreSQL 17 packages
  include_tasks: ../../../../tasks/install_ppg17.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-17/bin/postgresql-17-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  include_tasks: ../../../../tasks/start_postgres_with_diagnostics.yml
  vars:
    svc_name: postgresql-17
    svc_state: started
  when: ansible_os_family == "RedHat"

- name: Install PPG tools
  include_tasks: ../../../../tasks/install_ppg17_tools.yml

# =========Telemetry testcases
- name: Verify telemetry installation
  include_tasks: ../../../../tasks/verify_telemetry.yml

- name: Verify telemetry weak-dependency opt-out
  include_tasks: ../../../../tasks/verify_telemetry_weak_dependency.yml
  when: weak_dependency_expected | default(false)

- name: Install GCC Deb
  apt:
    name: gcc
  when: ansible_os_family == "Debian"

- name: Install GCC RHEL
  yum:
    name: gcc
  when: ansible_os_family == "RedHat"

- name: Create temporary directory for compilation
  command: mkdir /tmp/libpq_command_temp_dir

- name: Copy libpq source file
  copy:
    src: ../../common/files/lib_version.c
    dest: /tmp/libpq_command_temp_dir

- name: Delete dpkg-query for RHEL
  yum:
    name: dpkg
    state: absent
  when: ansible_os_family == "RedHat"
