"""Generate Jenkins job files (groovy pipelines + job-builder yml) from
scenario.yml jenkins sections.
"""
import argparse
import pathlib
import sys

import jinja2
import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent

HEADER_GROOVY = "// GENERATED by ppg-testing tools/gen_jenkins.py from %s/scenario.yml -- do not edit\n"
HEADER_YML = "# GENERATED by ppg-testing tools/gen_jenkins.py from %s/scenario.yml -- do not edit\n"

_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(str(REPO / "templates" / "jenkins")),
    keep_trailing_newline=True,
)


class GenJenkinsError(Exception):
    pass


def resolve_params(desc, flavor):
    out = []
    for p in desc.get("params", []):
        flavors = p.get("flavors", ["single", "parallel"])
        if flavor not in flavors:
            continue
        item = dict(p)
        desc_key = "description_%s" % flavor
        if desc_key in p:
            item["description"] = p[desc_key]
        default_key = "default_%s" % flavor
        if default_key in p:
            item["default"] = p[default_key]
        item.setdefault("quote", "'")
        out.append(item)
    return out


def generate(group_dir):
    """Return {filename: content} for every flavor's groovy + yml file."""
    group_dir = pathlib.Path(group_dir)
    desc_path = group_dir / "scenario.yml"
    desc = yaml.safe_load(desc_path.read_text())
    if "jenkins" not in desc:
        raise GenJenkinsError("%s: no 'jenkins' section, nothing to generate" % desc_path)
    jk = desc["jenkins"]
    rel = str(group_dir.relative_to(REPO)) if group_dir.is_relative_to(REPO) else str(group_dir)

    out = {}
    for flavor, job in jk["jobs"].items():
        ctx = dict(
            header=HEADER_GROOVY % rel,
            molecule_dir=jk["molecule_dir"],
            artifacts=jk["artifacts"],
            render_group=jk["molecule_dir"],
            display_name=job["display_name"],
            params=resolve_params(desc, flavor),
            slack=job.get("slack"),
        )
        try:
            groovy_template = _env.get_template("%s.groovy.j2" % flavor)
        except jinja2.TemplateNotFound:
            raise GenJenkinsError(
                "%s: no groovy template for jenkins job flavor %r "
                "(expected templates/jenkins/%s.groovy.j2)" % (desc_path, flavor, flavor)) from None
        groovy = groovy_template.render(**ctx)
        yml = _env.get_template("job.yml.j2").render(
            header=HEADER_YML % rel,
            job_name=job["job_name"],
            script_path="ppg/%s.groovy" % job["file"],
        )
        out["%s.groovy" % job["file"]] = groovy
        out["%s.yml" % job["file"]] = yml
    return out


def find_groups_with_jenkins():
    groups = []
    for p in REPO.rglob("scenario.yml"):
        rel = p.relative_to(REPO)
        if rel.parts[0] == "tools":
            continue
        desc = yaml.safe_load(p.read_text())
        if "jenkins" in desc:
            groups.append(p.parent)
    return sorted(groups, key=lambda g: str(g.relative_to(REPO)))


def resolve_group(g):
    p = pathlib.Path(g)
    return p if p.is_absolute() else (REPO / p)


def check_cmd(groups, jenkins_repo):
    drift = []
    for g in groups:
        files = generate(g)
        for name, content in sorted(files.items()):
            target = jenkins_repo / "ppg" / name
            if not target.exists():
                drift.append((target, "missing"))
                continue
            if target.read_text() != content:
                drift.append((target, "differs"))
    for target, reason in drift:
        print("DRIFT %s (%s)" % (target, reason))
    return 1 if drift else 0


def write_cmd(groups, jenkins_repo):
    for g in groups:
        files = generate(g)
        for name, content in sorted(files.items()):
            target = jenkins_repo / "ppg" / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
            print("wrote %s" % target)
    return 0


def build_argparser():
    ap = argparse.ArgumentParser(
        description="Generate Jenkins pg_tde job files from scenario.yml descriptors.")
    ap.add_argument("--jenkins-repo", required=True,
                     help="path to the jenkins-pipelines repo")
    ap.add_argument("--group", action="append", default=[],
                     help="group dir to generate, e.g. pg_tde/tde (repeatable); "
                          "default = every group whose scenario.yml has a jenkins section")
    ap.add_argument("--check", action="store_true",
                     help="diff mode: exit 1 and print DRIFT lines instead of writing")
    return ap


def main(argv=None):
    ap = build_argparser()
    args = ap.parse_args(argv)

    groups = [resolve_group(g) for g in args.group] if args.group else find_groups_with_jenkins()
    jenkins_repo = pathlib.Path(args.jenkins_repo)

    if args.check:
        return check_cmd(groups, jenkins_repo)
    return write_cmd(groups, jenkins_repo)


if __name__ == "__main__":
    sys.exit(main())
